sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
  irc:
    use_notice: true
    skip_join: true
    channels:
      secure: PvfRuDS/xREWahkngXhs63AwARz3J8zSvlhDT3uV0n1fHbaU/4VkAzv6MgHOQBQllNYBhPayGflcF77YRUxrATaSMDntElcSDSGsCCqO3oSPHOsQ3b7Tzkz0W/qcYkwCC4CuuOFTbA2+Uo26K0Y5KxPSfT0opyViFA7+uxa+3qpwQC3EtkUVtRntvumVuPKJLFGqoPd1Xz6U7ML8N63lZl/tCb5pc/j7gBBWjZX0GCoOMK5wEycFhAnDbZiypkUuD8tP/uHk4S7Y22ahORgITKLup+KIF9jEkyJR/f+mhjCYH/9Dilrxj9JIchs4PSiq3DDAHHsm4w/l9HW9LMO3Jep2RtDcIQVMAY15eVG1ih0DqT78uo2d3BggijVZH9nGh5eSevB1rpL2yDUd7Yd5msAZxak8VbUZP2hlCsOhrKeZzfY6BSI3V98jr2vuXImO7t1ouyXkC0TGJmtGBJSAVxZxbK3IcAlTIuza0QtbEXsPGtTOymsVXpFw9zx8SpDnNKeo8z4CZCGg6uLdUxSB3wWKCRwyQTE45iYA4LOgRycXVpWabuSN9AClk2P/82/64jjzVUgVzmTCcFk0v2uqp4By+3lEUQKp3w1mTUrkjTj3npRI10DX2Qpk4dRXZRiaYcFHHmptD/1qEtKpqrXi+lnsiaIa5WnEZTv6BTWS5C0=
node_js:
- '6'
- '5'
- '4'
- iojs-v3
- iojs-v2
- iojs-v1
- '0.12'
- '0.11'
- '0.10'
before_install:
- npm i -g npm@^2.0.0
before_script:
- npm prune
- export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
after_success:
- npm run coverage
- npm run coverage:upload
- curl -Lo travis_after_all.py https://git.io/travis_after_all
- python travis_after_all.py
- export $(cat .to_export_back) &> /dev/null
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
